### PR TITLE
Uniformisation of the findings remediation effort text

### PR DESCRIPTION
**Pull request by MaxNad**
If you create a new finding (or initially import the findings from the json file), the remediation efforts values are low, medium and hard.
remediation1

When the finding is already created and you go into the edit page, the values changes to Quick, Planned and Involved :
remediation2

The problem with that, is that when you generate the report with a mixture of manually created findings that you never edited, manually created findings that you edited at least one time, and imported findings, you will get a report with a table with both LOW and Quick.

I just standardized the texts. It will not fix the findings already in the template database, but it will correct the problem for new installations and new findings that are not edited before generation.

### CODE REVIEW

**Comment by MaxNad** [comment]
I have just seen that this issue is more relevant to DREAD as it allows the user to set the remediation effort when the finding is created.

**Comment by BuffaloWill** [comment]
Thanks @MaxNad. I agree, this issue would appear if someone created a finding with DREAD and then switched scores to CVSS or CVSSv3. Their finding would have the old effort value (unless they re-edit and save). 

AFAIK Microsoft doesn't have a standard for what remediation effort terming should be for DREAD so we could switch to Quick/Planned/Involved. I would prefer that we allow the user to set their own scoring in config.json; this is how default scoring is handled. Could you switch the code in views/create_finding.haml to:
```
          %select#effort{ :name => "effort" }
            - if @finding
              - settings.effort.each do |effort|
                - if effort == @finding.effort
                  %option{ :selected => "selected" } #{effort}
                - else
                  %option #{effort}
            - else
              - settings.effort.each do |effort|
                %option #{effort}
```

Otherwise I am good with it. Cheers and thank you for the PR!

**Comment by MaxNad** [comment]
I replaced the hard coded values at both places (DREAD and CVSS2).

I did not include the following piece of code since the views/create_findings.haml is never actually used to edit a finding (as far as I know). therefore, it would have never taken this path. `- if @finding
              - settings.effort.each do |effort|
                - if effort == @finding.effort
                  %option{ :selected => "selected" } #{effort}
                - else
                  %option #{effort}`

**Comment by BuffaloWill** [comment]
Good point. Thanks @MaxNad!

**Pull request merged**
