### PR TITLE
Added Finding Number to be used on report ie. "Finding 3"

### PR DESCRIPTION
**Pull request by geckom**
The will dynamically generate a auto incrementing finding number based on the order of the risk method chosen (ie. for CVSS it will give "Finding 1" to the highest CVSS number).

This was added so when you meaning a finding later in the report you can reference the finding number. So the client can say "I dont agree with finding 7" instead of "I dont agree with XSS on the blah"

There is no UI changes for this PR, but the variable if there if you want to use it.

### CODE REVIEW

**Comment by geckom** [comment]
Added to the wrong stream, but this also includes attachment captions. So you can add a comment to any attachment (and possible add that caption to the report)

**Comment by ITGSean** [comment]
Can't you just do this in Word as a custom numbered list?

**Comment by geckom** [comment]
You can, but in our reports we mention findings a in a couple of different places, because of this we reference by finding number. This is something serpico couldnt do, however this small change allows it. If you dont want to use it you just dont include the variable in your report.

**Comment by BuffaloWill** [comment]
Thanks @geckom!! Looks good, landing.

**Pull request merged**
