### PR TITLE
Moves Bundler to 2.x. Updates all Ruby versions to match Gemfile on master.

### PR DESCRIPTION
**Pull request by artis3n**
One of the more annoying issues I had with getting this project installed on Ruby 2.3.3 is that the project wouldn't build anymore without Bundler 2 (on the OS's I was using, at least) and Bundler 2 was only available on Ruby 2.3.8.

Now that Ruy 2.6.3 is in master (#564 ), ran `bundle --update bundler` to update the `Gemfile.lock` to use Bundler 2.

Also updated all files in the project to use Ruby 2.6.3 instead of 2.3.3.

### CODE REVIEW

**Comment by BuffaloWill** [comment]
Wow that was fast :smile:. Thanks for the PR, looks good to me.

**Comment by artis3n** [comment]
:sheepish: 🚀

**Comment by BuffaloWill** [comment]
Just rolled back the Bundler 2 requirement only because it was conflicting with Ruby 2.6.3 docker image and would've required an additional step in our Dockerfile to make compatible. 

If I am reading https://bundler.io/blog/2019/01/03/announcing-bundler-2.html correctly,  users should be able to use Bundler 1 or 2 now that we are on Ruby 2.6.3. Lmk if this isn't the case for you. 

Thanks again for the PR and we can merge the Bundler 2 update into the lockfile in the future.

**Comment by artis3n** [comment]
That makes sense. FWIW my Dockerfile looks like this. Can put it into a PR for testing if you would like.

```
FROM ruby:2.6.3
LABEL maintainer="<us>"

RUN apt-get update && apt-get -y upgrade
# Nokogiri dependencies
RUN apt-get install -y libreadline-dev libxml2 libxml2-dev libxml2-utils libxslt-dev
RUN apt-get install -y build-essential

ENV SRP_ROOT /Serpico
ENV SRP_ADMIN Administrator
ENV SRP_FINDINGS no

RUN mkdir $SRP_ROOT
WORKDIR $SRP_ROOT

COPY . $SRP_ROOT
COPY ./docker/docker.sh scripts/docker.sh

# Update bundler and install dependencies
# THIS would fix the bundler 2.x issue
RUN gem update --system
RUN gem install bundler
RUN bundle install

# Allow DB to be on a shared volume
VOLUME ["$SRP_ROOT/db", "$SRP_ROOT/templates", "$SRP_ROOT/attachments", "$SRP_ROOT/tmp"]
EXPOSE 8443

CMD bash scripts/docker.sh
```

**Pull request merged**
